"""add location system with types fields and values

Revision ID: 18c800399016
Revises: b62580483499
Create Date: 2025-11-17 16:01:36.276344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import GUID


# revision identifiers, used by Alembic.
revision: str = '18c800399016'
down_revision: Union[str, Sequence[str], None] = 'b62580483499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_types',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_types_id'), 'location_types', ['id'], unique=False)
    op.create_table('location_type_fields',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('location_type_id', GUID(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('STRING', 'NUMBER', name='fieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('regex_pattern', sa.String(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_type_id'], ['location_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_type_fields_id'), 'location_type_fields', ['id'], unique=False)
    op.create_index(op.f('ix_location_type_fields_location_type_id'), 'location_type_fields', ['location_type_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('organization_id', GUID(length=36), nullable=False),
    sa.Column('location_type_id', GUID(length=36), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_type_id'], ['location_types.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_location_type_id'), 'locations', ['location_type_id'], unique=False)
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('location_field_values',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('location_id', GUID(length=36), nullable=False),
    sa.Column('field_id', GUID(length=36), nullable=False),
    sa.Column('value_string', sa.String(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['location_type_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'field_id', name='uq_location_field')
    )
    op.create_index(op.f('ix_location_field_values_field_id'), 'location_field_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_location_field_values_id'), 'location_field_values', ['id'], unique=False)
    op.create_index(op.f('ix_location_field_values_location_id'), 'location_field_values', ['location_id'], unique=False)

    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('accessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', GUID(length=36), nullable=True))
        batch_op.create_foreign_key('fk_accessions_location_id', 'locations', ['location_id'], ['id'])

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', GUID(length=36), nullable=True))
        batch_op.alter_column('created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.alter_column('created_by',
                   existing_type=sa.VARCHAR(length=36),
                   nullable=False)
        batch_op.create_index(op.f('ix_plants_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_plants_location_id', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plants_location_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_plants_id'))
        batch_op.alter_column('created_by',
                   existing_type=sa.VARCHAR(length=36),
                   nullable=True)
        batch_op.alter_column('created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        batch_op.drop_column('location_id')

    with op.batch_alter_table('accessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accessions_location_id', type_='foreignkey')
        batch_op.drop_column('location_id')
    op.drop_index(op.f('ix_location_field_values_location_id'), table_name='location_field_values')
    op.drop_index(op.f('ix_location_field_values_id'), table_name='location_field_values')
    op.drop_index(op.f('ix_location_field_values_field_id'), table_name='location_field_values')
    op.drop_table('location_field_values')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_type_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_location_type_fields_location_type_id'), table_name='location_type_fields')
    op.drop_index(op.f('ix_location_type_fields_id'), table_name='location_type_fields')
    op.drop_table('location_type_fields')
    op.drop_index(op.f('ix_location_types_id'), table_name='location_types')
    op.drop_table('location_types')
    # ### end Alembic commands ###
