"""Add status field to organization memberships

Revision ID: 2b41fb4b4ed7
Revises: 4deb0f562b2f
Create Date: 2025-11-06 11:33:29.654714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b41fb4b4ed7'
down_revision: Union[str, Sequence[str], None] = '4deb0f562b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column with default value 'ACTIVE' for existing rows
    op.add_column('organization_memberships', sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', name='membershipstatus'), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_memberships', 'status')
    # ### end Alembic commands ###
