"""Add removed_at field to organization memberships

Revision ID: 5253f04e4e0c
Revises: 4deb0f562b2f
Create Date: 2025-11-06 16:21:58.090880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5253f04e4e0c'
down_revision: Union[str, Sequence[str], None] = '4deb0f562b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('removed_at', sa.DateTime(), nullable=True))

    # Only drop status column if it exists (it may not exist in fresh databases)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('organization_memberships')]
    if 'status' in columns:
        op.drop_column('organization_memberships', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('status', sa.VARCHAR(length=7), server_default=sa.text("'ACTIVE'"), nullable=False))
    op.drop_column('organization_memberships', 'removed_at')
    # ### end Alembic commands ###
