"""Add subspecies and cultivar to species

Revision ID: 795d2190152a
Revises: 6bf4364817b8
Create Date: 2025-11-20 13:57:38.557906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795d2190152a'
down_revision: Union[str, Sequence[str], None] = '6bf4364817b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('subspecies', sa.String(), nullable=True))
    op.add_column('species', sa.Column('cultivar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'cultivar')
    op.drop_column('species', 'subspecies')
    # ### end Alembic commands ###
