"""add select field type to location type fields

Revision ID: 98d464c324f3
Revises: 18c800399016
Create Date: 2025-11-17 22:01:27.726619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d464c324f3'
down_revision: Union[str, Sequence[str], None] = '18c800399016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_type_fields', sa.Column('field_options', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_type_fields', 'field_options')
    # ### end Alembic commands ###
