"""add event system tables

Revision ID: b62580483499
Revises: 189b5099b14b
Create Date: 2025-11-12 12:30:46.148491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import GUID


# revision identifiers, used by Alembic.
revision: str = 'b62580483499'
down_revision: Union[str, Sequence[str], None] = '189b5099b14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type for PostgreSQL (if it doesn't already exist)
    # This enum is shared with other tables (accession fields, plant fields)
    fieldtype_enum = sa.Enum('STRING', 'NUMBER', name='fieldtype')
    fieldtype_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_types_id'), 'event_types', ['id'], unique=False)
    op.create_table('event_type_fields',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('event_type_id', GUID(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', fieldtype_enum, nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('regex_pattern', sa.String(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_type_fields_event_type_id'), 'event_type_fields', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_event_type_fields_id'), 'event_type_fields', ['id'], unique=False)
    op.create_table('plant_events',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('plant_id', GUID(length=36), nullable=False),
    sa.Column('event_type_id', GUID(length=36), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_events_event_type_id'), 'plant_events', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_plant_events_id'), 'plant_events', ['id'], unique=False)
    op.create_index(op.f('ix_plant_events_plant_id'), 'plant_events', ['plant_id'], unique=False)
    op.create_table('event_field_values',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('event_id', GUID(length=36), nullable=False),
    sa.Column('field_id', GUID(length=36), nullable=False),
    sa.Column('value_string', sa.String(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['plant_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['event_type_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'field_id', name='uq_event_field')
    )
    op.create_index(op.f('ix_event_field_values_event_id'), 'event_field_values', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_field_values_field_id'), 'event_field_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_event_field_values_id'), 'event_field_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_field_values_id'), table_name='event_field_values')
    op.drop_index(op.f('ix_event_field_values_field_id'), table_name='event_field_values')
    op.drop_index(op.f('ix_event_field_values_event_id'), table_name='event_field_values')
    op.drop_table('event_field_values')
    op.drop_index(op.f('ix_plant_events_plant_id'), table_name='plant_events')
    op.drop_index(op.f('ix_plant_events_id'), table_name='plant_events')
    op.drop_index(op.f('ix_plant_events_event_type_id'), table_name='plant_events')
    op.drop_table('plant_events')
    op.drop_index(op.f('ix_event_type_fields_id'), table_name='event_type_fields')
    op.drop_index(op.f('ix_event_type_fields_event_type_id'), table_name='event_type_fields')
    op.drop_table('event_type_fields')
    op.drop_index(op.f('ix_event_types_id'), table_name='event_types')
    op.drop_table('event_types')
    # ### end Alembic commands ###
